const { Console } = require('console');

global.navigator = { appName: 'nodejs' }; // fake navigator object
global.window = {}; // fake window object
var JSEncrypt = require('jsencrypt').default;


//Client Side
function encryptmymessage(message){
//Public key generated using  "openssl rsa -in rsa.private -out rsa.public -pubout -outform PEM"
    const public_key = 'MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgG9j3oCgpkPoxakPHHOMSJ6m2gGNWijbpydnAJkll7AI8PyEHqsZhZApZqNurtwqs4jDcgaeEUn + 3RzMoguh / joel9Epna0NSxNZzrXPQ9hFxVLvCZopE84h + gc1YfHQ / o0CjefHtJIK95ulhuvm + Gr2azJdk / wIXa6oU46DC4QFAgMBAAE=' ;
    let encrypt = new JSEncrypt({ default_key_size: 512 });
    encrypt.setPublicKey(public_key);

    let cipher_text = encrypt.encrypt(message);
    return cipher_text;
}

//Server Side
function decryptmymessage(encodedmessage) {
    // "openssl genrsa -out rsa.private 1024"
    const private_key = 'MIICWwIBAAKBgG9j3oCgpkPoxakPHHOMSJ6m2gGNWijbpydnAJkll7AI8PyEHqsZhZApZqNurtwqs4jDcgaeEUn + 3RzMoguh / joel9Epna0NSxNZzrXPQ9hFxVLvCZopE84h + gc1YfHQ / o0CjefHtJIK95ulhuvm + Gr2azJdk / wIXa6oU46DC4QFAgMBAAECgYBDc2E32I / 1zU1r6weafJc44uZeTD8NQL0 + YeP92MK6yR9MeaCskR7MxhUt4AcosP7YUSmKEkt72EYCe3Ogwa5UqAGiWgyk5dxP + lSIhXNWnNmDx1IIpPMRg0R7AKl7rmoDpb8QOSmpemmi1JtNnP01vK3fN6DAaI8jXzROLeJuvQJBANGr3BexxH5O / 9CGNxvPGOH1LMxwxbJhYRHMbsWoPkNqg2EBK7c / a + GpavsEoTgsq2RkTdxVYMyVQzV2uKVY6x8CQQCIALG + u2YU1mD + SnuUM + xRiYI3BXzI1JYjxOxLwKqA07aL2eLqftI1zMXH + 1buVLnz1iNbtSIV4ypJdQA4ghBbAkAZ2AMi8Ih1wSsK + uAkD1zTzTKeaHAV0qbyWK52sowqJyDWfhxzU9 / qSsWi9ykgEXF2yF5IgEWUMfm8x0tvJgylAkAVua6rHjp3V6uU04ccLJMyjznK2kiNuE / nlNx + WV + jRq6hdoPmG64uw / BQOtkvJz + xMOLjEnNIdcpag6MuY7CDAkEAlon4yZvgip09Ehsba2E9A1LrKcPiTiEehMz6QEVLC6B0W5NLHndz6EN8W / 1313VL + UPDObIAIn3LoZFuDi / x6A ==';
    console.log("EncodedMessage:"+encodedmessage)
    let decrypt = new JSEncrypt({ default_key_size: 512 });
    decrypt.setPrivateKey(private_key);

    let result = decrypt.decrypt(encodedmessage);
    return result;
}


let message="Aliens are coming";
console.log("Initial Message is:"+ message);
//Encryption generated by client
let encMess=encryptmymessage(message);

//Decrypting the encoded message by Server
let myMessage=decryptmymessage(encMess);
console.log("Message after decryption:" + myMessage);
